---
# author: lework

- name: install | Check if nexus local file is already configured.
  stat: path={{ nexus_file_path }}
  connection: local
  register: nexus_file_result

- name: install | Create software directory.
  file: path={{ software_files_path }} state=directory
  connection: local
  when: not nexus_file_result.stat.exists
  
- name: install | Download nexus file.
  get_url: url={{ nexus_file_url }} dest={{ software_files_path }} validate_certs=no
  connection: local
  when: not nexus_file_result.stat.exists

- name: install | Confirm the existence of the installation directory.
  file: path={{ software_install_path }} state=directory

- name: install | Copy nexus file to agent.
  unarchive:
    src: "{{ nexus_file_path }}"
    dest: "{{ software_install_path }}"
    creates: "{{ software_install_path }}/nexus-{{ nexus_version }}"

- name: install | Create nexus group.
  group: name={{ nexus_group }}

- name: install | Create nexus user.
  user: name={{ nexus_user }} group={{ nexus_group }}
  
- name: install | Set the owner of the nexus directory.
  file: path={{ software_install_path }}/nexus-{{ nexus_version }} state=directory owner={{ nexus_user }} group={{ nexus_group }} recurse=yes

- name: install | Create nexus dir soft link.
  file: src={{ software_install_path }}/nexus-{{ nexus_version }} dest={{ software_install_path }}/nexus owner={{ nexus_user }} group={{ nexus_group }} state=link
