---
# author: lework

- name: install | Check if kafka local file is already configured.
  stat: path={{ kafka_file_path }}
  connection: local
  register: kafka_file_result

- name: install | Create software directory.
  file: path={{ software_files_path }} state=directory
  connection: local
  when: not kafka_file_result.stat.exists

- name: install | Download kafka file.
  get_url: url={{ kafka_file_url }} dest={{ software_files_path }}
  connection: local
  when: not kafka_file_result.stat.exists

- name: install | Confirm the existence of the installation directory.
  file: path={{ software_install_path }} state=directory

- name: install | Copy kafka file to agent.
  unarchive:
    src: "{{ kafka_file_path }}"
    dest: "{{ software_install_path }}"
    creates: "{{ software_install_path }}/{{ kafka_file | splitext | first }}"
    
- name: Create kafka dir soft link.
  file: src={{ software_install_path }}/{{ kafka_file | splitext | first }} dest={{ kafka_home }} state=link
  
- name: "install | Create {{ kafka_user }} group."
  group: name={{ kafka_user }}

- name: "install | Create {{ kafka_user }} user."
  user: name={{ kafka_user }} group={{ kafka_user }} shell=/sbin/nologin

- name: install | Config environment variable.
  lineinfile: dest=/etc/profile line='export PATH={{ software_install_path }}/{{ kafka_file | splitext | first }}/bin/:$PATH'
