---
# author: lework

- name: install | Check if msyql file is already configured.
  stat: path={{ mysql_file_path }}
  connection: local
  register: mysql_file_result

- name: install | Create software directory.
  file: path={{ software_files_path }} state=directory
  connection: local
  when: not mysql_file_result.stat.exists

- name: install | Download mysql file.
  get_url: url={{ mysql_file_url }} dest={{ software_files_path }}
  connection: local
  when: not mysql_file_result.stat.exists and mysql_install_from_source

- name: install | Confirm the existence of the installation directory.
  file: path={{ software_install_path }} state=directory

- name: install | Not found mysql bin file.
  fail: msg={{ mysql_file_path }}
  when: not mysql_file_result.stat.exists and not mysql_install_from_source
  
- name: install | Ensure mysql libs and devel packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - mysql-libs
   - mysql-devel
   - gcc
   - bison
   - openssl
   - openssl-devel
   - ncurses
   - ncurses-devel
   - make
   - cmake
   - autoconf

- name: install | Create mysql group.
  group: name=mysql state=present

- name: install | Create mysql user.
  user: name=mysql shell=/sbin/nologin group=mysql

- block: 
  - name: install | Copy mysql source files to agent.
    unarchive: src={{ mysql_file_path }} dest=/tmp/ creates=/tmp/{{ mysql_dirname }}
  
  - name: install | Build configure script.
    shell: >
      {{ mysql_source_configure_command }}
      chdir=/tmp/{{ mysql_dirname }}
     
  - name: install | Make and install mysql.
    shell: make && make install chdir=/tmp/{{ mysql_dirname }}
  when: mysql_install_from_source
  
- name: install | Copy mysql bin files to agent.
  unarchive: src={{ mysql_file_path }}  dest={{ software_install_path }} creates={{ mysql_basedir }}/bin/mysql
  when: not mysql_install_from_source
  
- name: install | Create mysql dir soft link.
  file: src={{ software_install_path }}/{{ mysql_dirname }} dest={{ mysql_basedir }} state=link

- name: install | Config environment variable.
  lineinfile: dest=/etc/profile line='export PATH={{ mysql_basedir }}:$PATH'
