---
# author: lework

- name: install | Check if zookeeper local file is already configured.
  stat: path={{ zookeeper_file_path }}
  connection: local
  register: zookeeper_file_result

- name: install | Create software directory.
  file: path={{ software_files_path }} state=directory
  connection: local
  when: not zookeeper_file_result.stat.exists

- name: install | Download zookeeper file.
  get_url: url={{ zookeeper_file_url }} dest={{ software_files_path }}
  connection: local
  when: not zookeeper_file_result.stat.exists

- name: install | Confirm the existence of the installation directory.
  file: path={{ software_install_path }} state=directory

- name: install | Copy zookeeper file to agent.
  unarchive:
    src: "{{ zookeeper_file_path }}"
    dest: "{{ software_install_path }}"
    creates: "{{ software_install_path}}/zookeeper-{{ zookeeper_version }}"

- name: install | Check if zookeeper remote soft link is already configured.
  stat: path="{{ software_install_path }}/zookeeper"
  register: zookeeper_soft_link_result

- name: install | Create zookeeper dir soft link.
  file: "src={{ software_install_path }}/zookeeper-{{ zookeeper_version }} dest={{ software_install_path }}/zookeeper state=link"
  when: not zookeeper_soft_link_result.stat.exists

- name: "install | Create {{ zookeeper_user }} group."
  group: name={{ zookeeper_user }}

- name: "install | Create {{ zookeeper_user }} user."
  user: name={{ zookeeper_user }} group={{ zookeeper_user }} shell=/sbin/nologin

- name: install | Config environment variable.
  lineinfile: dest=/etc/profile line='export PATH={{ software_install_path }}/zookeeper/bin/:$PATH'
