---
# author: lework

- name: install | Check if filebeat local file is already configured.
  stat: path={{ filebeat_file_path }}
  connection: local
  register: filebeat_file_result

- name: install | Create software files path.
  file: path={{ software_files_path }} state=directory
  connection: local
  when: not filebeat_file_result.stat.exists

- name: install | Download filebeat file.
  get_url: url={{ filebeat_file_url }} dest={{ software_files_path }} validate_certs=no
  connection: local
  when: not filebeat_file_result.stat.exists

- name: install | Confirm the existence of the installation directory.
  file: path={{ software_install_path }} state=directory

- name: install | Copy filebeat file to agent.
  unarchive:
    src: "{{ filebeat_file_path }}"
    dest: "{{ software_install_path }}"
    creates: "{{ filebeat_file | replace('.tar.gz','') }}"

- name: install | Check if filebeat remote soft link is already configured.
  stat: path={{ filebeat_home_dir }}
  register: filebeat_soft_link_result

- name: install | Create filebeat dir soft link.
  file: "src={{ filebeat_file | replace('.tar.gz','') }} dest={{ filebeat_home_dir }} state=link"
  when: not filebeat_soft_link_result.stat.exists
